### ISSUE TITLE
"LiJ_2014" dataset

### ISSUE THREAD

**Issue by edoardopasolli** [waldronlab/curatedMetagenomicDataCuration#8] opened 2017-12-07 19:46 UTC
It seems that the "LiJ_2014" overlaps in some way with three other datasets: "LeChatelierE_2013", "NielsenHB_2014", "QinJ_2012".
More curation of the fields "sampleID" and "subjectID" is necessary

**Comment by lwaldron** [comment] 2018-01-03 13:20
We will start a duplicates table, rather than changing sampleID and subjectID identifiers.

**Comment by lwaldron** [comment] 2018-01-10 10:57
Duplicate of #14

**Closed by lwaldron** 2018-01-10 10:57 UTC
Labels: duplicate
