### ISSUE TITLE
number_bases and median_read_length

### ISSUE THREAD

**Issue by edoardopasolli** [waldronlab/curatedMetagenomicDataCuration#4] opened 2017-12-07 19:39 UTC
in the "number_bases" and "median_read_length" fields some samples have "NA"

**Comment by lwaldron** [comment] 2018-01-10 10:59
@schifferl I assume this is occurring in the R pipeline - can you identify why?

**Comment by schifferl** [comment] 2018-01-10 15:22
@lwaldron I had another look at the `template.csv` file and some of the curation files, as well as the `R` pipeline – the cause of this issue is not readily apparent. I think it is likely due to changes that have happened over time and would be resolved in running the entire pipeline again. @edoardopasolli is there a specific dataset you are referring to?

**Comment by edoardopasolli** [comment] 2018-01-10 15:39
most of the datasets are currently affected by this problem

**Comment by schifferl** [comment] 2018-01-18 18:56
Since this is not a curation issue and has no identifiable cause I am going to close the issue. I know it is still an issue but it will be resolved with a unit test that checks the final data in the package against the curated metadata here (https://github.com/waldronlab/curatedMetagenomicData/issues/109).

**Comment by edoardopasolli** [comment] 2018-03-06 11:19
"number_bases" and "median_read_length" fields have been fixed for all datasets. this issue can be closed definitevely.

**Closed** 2018-03-06 11:20 UTC
Labels: bug
